# Config file for automatic testing at travis-ci.org

language: python
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
python:
  - "3.6"
  - "3.5"
  - "2.7"
  - "pypy"

install:
  - pip install -U .
  - pip install -U -r dev-requirements.txt

before_script: flake8
script: py.test

# Auto-release to PyPI when tag is pushed
jobs:
  include:
  - stage: PyPI Release
    if: tag IS present
    python: "3.6"
    env: []
    # Override before_script, install, and script to no-ops
    before_script: true
    install: true
    script: echo "Releasing to PyPI..."
    after_success: true
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: oYZ97xz/ZhylohjrvClpFOURvlXCxFig4KMfAg0cuuL1TLNXalAnYnWebZN9srVmBDZ324aAHt9VZnCtZCXORhkMTDsBTnOrWkb0jsnxFN2PFP9KARLltiVknvTZb6Uy70XsMlKW920CWUKI+voAI9agbUETaxtc212jo3yHkxYQGtfTfURfQCZhYYoLK45v04Rm/HSQHGgUlg8xOJm/uJTC2xpPOWJv3XkoXfS18p0g0IsrVbtNdAvJ+IOJbRig2Qoq0vMXiNMArJPDTP1scjME5qKexN+5UpVzsUfm6254PK0d/Ap2DMOcZVPlxXIIMHoN5gpwOSN3SAtfbb5NvJbtNRjB12erzw+0DtB8ibJ3DxrOMJAihXkd8REIcqOU3Hsmh+1PKUkYfHjbk0SUb0AupllxgiP1Bp5fQBwPEp+he9atJAkAY9hr7EK0JqQ12DrtUgQ9kqDbz26Ad0II4R9M7xfJdPRljS9QY9RjTemnlcM+4rya7PzmblYqAYjedfb5zSAdyTEY9Px/e8pscKdpisLPGHpnwFCoAlaGtq5NzmzcqaoRImkl6B3YloapuCTs8RVwP0Me42qXSuGr+ocZTumxvt9a8bwoMOxyZX6Il65JmwaiR2BLY8cRjl9AQKhWcAyjNXYCdn454xO3QMtFhqm3+1zmEdHcltbdCVY=
